---
- name: Restart nginx service
  set_fact:
    nginx_state: restarted
  changed_when: true
  notify: Reload nginx service

- name: Reload nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    state: "{{ nginx_state | default('reloaded') }}"
  become: yes